### ISSUE TITLE
Consider using tzf-rs for coordinates to timezone mapping

### ISSUE THREAD

**Issue by diogotcorreia** [maxbrunet/automatic-timezoned#314]
**Is your feature request related to a problem? Please describe.**
Yes! Since [tzdata 2022b](https://github.com/eggert/tz/blob/5a43b0d7d6fd80b380a7f67f975ac91c1bcb074a/NEWS#L526-L538), some timezones are [no longer included](https://github.com/eggert/tz/commit/35fa37fbbb152f5dbed4fd5edfdc968e3584fe12#diff-e70a6a49fda6ded957afdbf28fa2b503a37dd9739d411fd43a7ea9d8df26eef4L304) in the `zone1970.tab` file (such as `Europe/Stockholm`). I was erroneously getting my timezone set to `Europe/Tallinn` (while my location is Stockholm) because of this.

Another problem that can occur with the current distance-based solution is that a user near the border of a timezone might get the incorrect one, depending on the exact coordinates of each timezone.

**Describe the solution you'd like**
Instead of using distance to figure out the timezone from the coordinates, use timezone borders, for example, through [tzf-rs](https://github.com/ringsaturn/tzf-rs) (data from [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder)).

**Describe alternatives you've considered**
My alternative at the moment is to [use the `zone.tab` file](https://github.com/diogotcorreia/dotfiles/commit/91ea585125948c12f8d1a505455fde0df8d6be89), which is deprecated, because it includes the deleted timezones.

**Additional context**
Nothing that I can think of right now. I just want to thank you for this awesome project!
Let me know if you need more information or help with anything.

**Comment by maxbrunet** [comment]
Hey @diogotcorreia :wave:, thank you so much for reporting this and all the details. It is unfortunate, I do like the idea of separating the program from TZ locations, but it seems like it is becoming impossible. This new `tzf-rs` crate looks really nifty. I will not have time to look into the issue myself immediately, but if you or someone else have time, a PR would be welcome.

**Comment by diogotcorreia** [comment]
@maxbrunet Thank you for your input! I'll see if I can submit a PR tomorrow, it hopefully won't take too long :)

**Comment by diogotcorreia** [comment]
Would you prefer that I remove the tzdata implementation and rely solely on `tzf-rs`, or would you like to keep both as an option?

**Comment by maxbrunet** [comment]
Thank you for your help, I think we could do with `tzf-rs` only as a breaking change and it will start v2. Take your time, I probably will not be able to review the PR immediately either :slightly_smiling_face:
