### ISSUE TITLE
Geoclue not providing location anymore

### ISSUE THREAD

**Issue by poperigby** [maxbrunet/automatic-timezoned#424]
I'm running the [NixOS module](https://github.com/NixOS/nixpkgs/blob/7eee17a8a5868ecf596bbb8c8beb527253ea8f4d/nixos/modules/services/system/automatic-timezoned.nix), and it's not setting my timezone to anything. `timedatectl` reports my timezone as UTC. How can I debug?

**Comment by maxbrunet** [comment]
Hey @poperigby, I think the issue you're seeing is not with `automatic-timezoned`, but with `geoclue2`, Mozilla has retired its location service, please see NixOS/nixpkgs#321121 for details

`automatic-timezoned` is simply waiting for `geoclue2` to return a location, you can confirm the issue with `journalctl --unit=geoclue`, you should see something like:

```
Failed to query location: Error resolving “location.services.mozilla.com”: Name or service not known
Failed to query location: Query location SOUP error: Not Found
```

**Comment by poperigby** [comment]
Ah, that makes sense. Thank you.
