### ISSUE TITLE
Cannot change timezone because : Interactive authentication required

### ISSUE THREAD

**Issue by GreyXor** [maxbrunet/automatic-timezoned#443]
Hello,
I change my timezone with : `timedatectl set-timezone`
but when I run `automatic-timezoned`. I got this error
```
[INFO  automatic_timezoned] Starting automatic-timezoned 2.0.43...
[DEBUG automatic_timezoned] Received location update. Latitude: 60.89765154840812 / Longitude: 7.09806
Error: MethodError(OwnedErrorName("org.freedesktop.DBus.Error.InteractiveAuthorizationRequired"), Some("Interactive authentication required."), Msg { type: Error, serial: 29, sender: UniqueName(":1.741"), reply-serial: 13, body: Str, fds: [] })
```
**automatic-timezoned version**
2.0.43

**Linux distribution**
 Arch Linux 6.13rc4

**Comment by maxbrunet** [comment]
Hey @GreyXor

Does `automatic-timezoned` run as `root` or is there a Polkit rule for the user?

https://github.com/maxbrunet/automatic-timezoned/blob/500bda4e30ab1bc986e0d46b0cb74156eb34f976/README.md#L22

Here is an example of Polkit rule:

https://github.com/maxbrunet/automatic-timezoned/blob/500bda4e30ab1bc986e0d46b0cb74156eb34f976/examples/polkit.rules#L3-L8

**Comment by GreyXor** [comment]
even as root it's not working neither. I didn't tried with the udev rule

**Comment by maxbrunet** [comment]
> Any idea why it's not working with root?

It seems to be hanging on obtaining the location, it could be the absence of a GeoClue agent running as `root`  

https://github.com/maxbrunet/automatic-timezoned/blob/500bda4e30ab1bc986e0d46b0cb74156eb34f976/README.md#L23-L24

**Comment by GreyXor** [comment]
thanks
